#Should I use here also 'production' and 'development' ?

loglevel: info
logfile: './logs/dev-logs.log'
enableLogs: true
strictCheck: false
controllers: 'C:\Users\ipelu\OneDrive\Documentos\GitHub\project-oas-tools\example\controllers'
