#THIS FILE MUST CONTAIN ALL THE CONFIGURATION VARIABLES! as it will be used as the default configs so it must initialize all of them.

production:
  loglevel: info
  logfile: './logs/pro-logs.log'
  strict: false
  router: true
  validator: true

development:
  loglevel: debug
  logfile: './logs/dev-logs.log'
  strict: false
  controllers: '../../tests/testServer/controllers' #once I find out how to use user's index.js __dirname in my module's index.js I must remove this line
  router: true
  validator: true


# loglevel: info -> prints all but debug logs
# loglevel: debug -> prints all logs
# loglevel: error -> prints only error logs
